version: 0.2

env:
  secrets-manager:
    SSH_KEY: 'fe-ec2-ssh-key'

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "📦 Installing dependencies..."
      - npm ci
      - set -eo pipefail
      - yum -y update || true
      - yum -y install yum-utils jq zip openssh-client || true

  build:
    commands:
      - echo "🏗️ Building Next.js project (with .env)..."
      - ls -al
      - if [ ! -f .env ]; then echo "⚠️ No .env file found!"; fi
      - npm run build
      - echo "✅ Build complete"

      - echo "📦 Zipping full project for deployment..."
      - zip -r build.zip . -x "*.git*" "node_modules/*" "build.zip"

  post_build:
    commands:
      - echo "🚀 Deploying to EC2..."
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/home-keypair.pem
      - chmod 600 ~/.ssh/home-keypair.pem

      - echo "🔑 Testing SSH connection..."
      - ssh -i ~/.ssh/home-keypair.pem -o StrictHostKeyChecking=no ubuntu@54.169.171.227 "echo '✅ Connected to EC2'"

      - ssh -i ~/.ssh/home-keypair.pem -o StrictHostKeyChecking=no ubuntu@54.169.171.227 "rm -R /home/ubuntu/frontend"
      - ssh -i ~/.ssh/home-keypair.pem -o StrictHostKeyChecking=no ubuntu@54.169.171.227 "mkdir -p /home/ubuntu/frontend"

      - echo "📤 Uploading project to EC2..."
      - scp -i ~/.ssh/home-keypair.pem -o StrictHostKeyChecking=no build.zip ubuntu@54.169.171.227:/home/ubuntu/frontend/

      - echo "🧩 Copying build script..."
      - scp -i keypair.pem -o StrictHostKeyChecking=no deploy.sh ubuntu@54.169.171.227:/home/ubuntu/

      - |
        echo "Creating file .env..."
        cat << EOF > .env
        NODE_ENV=${NODE_ENV}

        FRONTEND_SERVER_URL=${FRONTEND_SERVER_URL}
        BACKEND_SERVER_URL=${BACKEND_SERVER_URL}
        BACKEND_API_KEY=${BACKEND_API_KEY}

        # AWS Configuration
        AWS_REGION=${AWS_REGION}

        # AWS Cognito
        COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
        COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
        COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}

        # For metric
        METRIC_ACCESS_KEY=${METRIC_ACCESS_KEY}
        METRIC_SECRET_KEY=${METRIC_SECRET_KEY}
        EOF

      # Copy file .env
      - scp -i keypair.pem -o StrictHostKeyChecking=no .env ubuntu@54.169.171.227:/home/ubuntu/frontend/

      - echo "Execute deploy.sh on EC2..."
      - |
        ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@54.169.171.227 "
          chmod +x /home/ubuntu/deploy.sh
          /home/ubuntu/deploy.sh
        "

      - echo "✅ Deployment completed successfully!"

artifacts:
  files:
    - build.zip
