version: 0.2

env:
  secrets-manager:
    SSH_KEY: 'fe-ec2-ssh-key'

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "📦 Installing dependencies..."
      - npm ci
      - set -eo pipefail
      - yum -y update || true
      - yum -y install yum-utils jq zip openssh-client || true

  build:
    commands:
      - echo "🏗️ Building Next.js project (with .env)..."
      - ls -al
      - if [ ! -f .env ]; then echo "⚠️ No .env file found!"; fi
      - npm run build
      - echo "✅ Build complete"

      - echo "📦 Zipping full project for deployment..."
      - zip -r build.zip . -x "*.git*" "node_modules/*" "build.zip"

  post_build:
    commands:
      - rm -R /home/ubuntu/frontend
      - mkdir -p /home/ubuntu/frontend
      - echo "🚀 Deploying to EC2..."
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/home-keypair.pem
      - chmod 600 ~/.ssh/home-keypair.pem

      - echo "🔑 Testing SSH connection..."
      - ssh -i ~/.ssh/home-keypair.pem -o StrictHostKeyChecking=no ubuntu@54.169.171.227 "echo '✅ Connected to EC2'"

      - echo "📤 Uploading project to EC2..."
      - scp -i ~/.ssh/home-keypair.pem -o StrictHostKeyChecking=no build.zip ubuntu@54.169.171.227:/home/ubuntu/frontend/

      - echo "🧩 Extracting & building on EC2..."
      - ssh -i ~/.ssh/home-keypair.pem -o StrictHostKeyChecking=no ubuntu@54.169.171.227 "
        set -e
        echo '📂 Switching to /home/ubuntu/frontend'
        cd /home/ubuntu/frontend
        unzip -o build.zip
        echo '📦 Installing dependencies...'
        npm ci --omit=dev
        echo '🏗️ Rebuilding Next.js project on EC2...'
        npm run build
        echo '🚀 Starting app with PM2...'
        pm2 delete frontend || true
        pm2 start npm --name frontend -- run start -- -H 0.0.0.0
        pm2 save
        "

      - echo "✅ Deployment completed successfully!"

artifacts:
  files:
    - build.zip
