import { AwsService } from '@/features/aws/services/libs/types'

export const awsServiceData: AwsService[] = [
  {
    id: 'iam-role',
    resourceType: 'AWS::IAM::Role',
    displayName: 'IAM Role',
    connections: ['ec2-instance', 'lambda', 'apigw'],
    requiredProps: ['AssumeRolePolicyDocument'],
    requiredConnections: [],
    recommendedConnections: ['lambda', 'ec2', 'step-functions'],
  },
  {
    id: 'ec2-instance',
    resourceType: 'AWS::EC2::Instance',
    displayName: 'EC2 Instance',
    connections: ['iam-role', 'elastic-ip', 'ebs', 'efs', 'subnet', 'sg'],
    requiredProps: ['ImageId', 'InstanceType'],
    requiredConnections: ['subnet'],
    recommendedConnections: ['sg', 'iam-role', 'ebs'],
  },
  {
    id: 'elastic-ip',
    resourceType: 'AWS::EC2::EIP',
    displayName: 'Elastic IP',
    connections: ['ec2-instance', 'nat-gateway'],
    requiredProps: [],
    requiredConnections: ['ec2', 'nat-gateway'],
    recommendedConnections: [],
  },
  {
    id: 'ebs',
    resourceType: 'AWS::EC2::Volume',
    displayName: 'EBS Volume',
    connections: ['ec2-instance'],
    requiredProps: ['AvailabilityZone', 'Size'],
    requiredConnections: ['ec2'],
    recommendedConnections: [],
  },
  {
    id: 'efs',
    resourceType: 'AWS::EFS::FileSystem',
    displayName: 'EFS',
    connections: ['ec2-instance'],
    requiredProps: [],
    requiredConnections: ['subnet', 'sg'],
    recommendedConnections: ['ec2'],
  },
  {
    id: 'elb',
    resourceType: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
    displayName: 'Elastic Load Balancer',
    connections: ['ec2-instance', 'asg', 'subnet', 'sg'],
    requiredProps: ['Type'],
    requiredConnections: ['subnet', 'sg'],
    recommendedConnections: ['ec2', 'asg'],
  },
  {
    id: 'asg',
    resourceType: 'AWS::AutoScaling::AutoScalingGroup',
    displayName: 'Auto Scaling Group',
    connections: ['ec2-instance', 'elb', 'subnet'],
    requiredProps: ['MinSize', 'MaxSize', 'DesiredCapacity'],
    requiredConnections: ['subnet', 'launch-config'],
    recommendedConnections: ['elb'],
  },
  {
    id: 'rds',
    resourceType: 'AWS::RDS::DBInstance',
    displayName: 'RDS Instance',
    connections: ['subnet', 'sg'],
    requiredProps: ['DBInstanceClass', 'Engine', 'MasterUsername', 'MasterUserPassword'],
    requiredConnections: ['subnet', 'sg'],
    recommendedConnections: [],
  },
  {
    id: 'aurora',
    resourceType: 'AWS::RDS::DBCluster',
    displayName: 'Aurora Cluster',
    connections: ['subnet', 'sg'],
    requiredProps: ['Engine'],
    requiredConnections: ['subnet', 'sg'],
    recommendedConnections: [],
  },
  {
    id: 'elasticache',
    resourceType: 'AWS::ElastiCache::CacheCluster',
    displayName: 'ElasticCache',
    connections: ['subnet', 'sg'],
    requiredProps: ['Engine', 'CacheNodeType', 'NumCacheNodes'],
    requiredConnections: ['subnet', 'sg'],
    recommendedConnections: [],
  },
  {
    id: 's3',
    resourceType: 'AWS::S3::Bucket',
    displayName: 'S3 Bucket',
    connections: ['cloudfront', 'lambda', 'apigw'],
    requiredProps: [],
    requiredConnections: [],
    recommendedConnections: ['cloudfront'],
  },
  {
    id: 'cloudfront',
    resourceType: 'AWS::CloudFront::Distribution',
    displayName: 'CloudFront',
    connections: ['s3'],
    requiredProps: ['Enabled'],
    requiredConnections: ['s3'],
    recommendedConnections: [],
  },
  {
    id: 'sqs',
    resourceType: 'AWS::SQS::Queue',
    displayName: 'SQS Queue',
    connections: ['lambda', 'sns'],
    requiredProps: [],
    requiredConnections: [],
    recommendedConnections: ['lambda', 'sns'],
  },
  {
    id: 'sns',
    resourceType: 'AWS::SNS::Topic',
    displayName: 'SNS Topic',
    connections: ['sqs', 'lambda'],
    requiredProps: [],
    requiredConnections: [],
    recommendedConnections: ['sqs', 'lambda'],
  },
  {
    id: 'kinesis',
    resourceType: 'AWS::Kinesis::Stream',
    displayName: 'Kinesis Data Stream',
    connections: ['lambda'],
    requiredProps: ['ShardCount'],
    requiredConnections: [],
    recommendedConnections: ['lambda'],
  },
  {
    id: 'mq',
    resourceType: 'AWS::AmazonMQ::Broker',
    displayName: 'Amazon MQ',
    connections: ['lambda'],
    requiredProps: ['EngineType', 'EngineVersion', 'HostInstanceType'],
    requiredConnections: ['subnet', 'sg'],
    recommendedConnections: [],
  },
  {
    id: 'apigw',
    resourceType: 'AWS::apigw::RestApi',
    displayName: 'API Gateway',
    connections: ['lambda', 's3'],
    requiredProps: ['Name'],
    requiredConnections: ['lambda'],
    recommendedConnections: [],
  },
  {
    id: 'lambda',
    resourceType: 'AWS::Lambda::Function',
    displayName: 'Lambda Function',
    connections: ['s3', 'sns', 'sqs', 'apigw', 'iam-role', 'step-functions'],
    requiredProps: ['Handler', 'Runtime'],
    requiredConnections: ['iam-role'],
    recommendedConnections: ['subnet', 'sg'],
  },
  {
    id: 'step-functions',
    resourceType: 'AWS::StepFunctions::StateMachine',
    displayName: 'Step Functions',
    connections: ['lambda'],
    requiredProps: ['DefinitionString', 'RoleArn'],
    requiredConnections: ['lambda'],
    recommendedConnections: [],
  },
  {
    id: 'cognito',
    resourceType: 'AWS::Cognito::UserPool',
    displayName: 'Cognito User Pool',
    connections: ['apigw', 'lambda'],
    requiredProps: ['UserPoolName'],
    requiredConnections: [],
    recommendedConnections: ['lambda'],
  },
  {
    id: 'dynamodb',
    resourceType: 'AWS::DynamoDB::Table',
    displayName: 'DynamoDB',
    connections: ['lambda'],
    requiredProps: ['AttributeDefinitions', 'KeySchema', 'BillingMode'],
    requiredConnections: [],
    recommendedConnections: ['lambda'],
  },
  {
    id: 'documentdb',
    resourceType: 'AWS::DocDB::DBCluster',
    displayName: 'DocumentDB',
    connections: ['subnet', 'sg'],
    requiredProps: ['EngineVersion'],
    requiredConnections: ['subnet', 'sg'],
    recommendedConnections: [],
  },
  {
    id: 'neptune',
    resourceType: 'AWS::Neptune::DBCluster',
    displayName: 'Neptune',
    connections: ['subnet', 'sg'],
    requiredProps: [],
    requiredConnections: ['subnet', 'sg'],
    recommendedConnections: [],
  },
  {
    id: 'timestream',
    resourceType: 'AWS::Timestream::Database',
    displayName: 'Timestream',
    connections: [],
    requiredProps: ['DatabaseName'],
    requiredConnections: [],
    recommendedConnections: [],
  },
  {
    id: 'athena',
    resourceType: 'AWS::Athena::WorkGroup',
    displayName: 'Athena',
    connections: ['s3'],
    requiredProps: ['Name'],
    requiredConnections: ['s3'],
    recommendedConnections: [],
  },
  {
    id: 'redshift',
    resourceType: 'AWS::Redshift::Cluster',
    displayName: 'Redshift',
    connections: ['subnet', 'sg'],
    requiredProps: [
      'ClusterType',
      'NodeType',
      'NumberOfNodes',
      'MasterUsername',
      'MasterUserPassword',
    ],
    requiredConnections: ['subnet', 'sg'],
    recommendedConnections: [],
  },
  {
    id: 'opensearch',
    resourceType: 'AWS::OpenSearchService::Domain',
    displayName: 'OpenSearch',
    connections: ['subnet', 'sg'],
    requiredProps: ['DomainName'],
    requiredConnections: ['subnet', 'sg'],
    recommendedConnections: [],
  },
  {
    id: 'cloudwatch',
    resourceType: 'AWS::CloudWatch::Alarm',
    displayName: 'CloudWatch',
    connections: ['lambda', 'ec2-instance', 'rds'],
    requiredProps: ['MetricName', 'Namespace', 'ComparisonOperator', 'Threshold'],
    requiredConnections: [],
    recommendedConnections: [],
  },
  {
    id: 'cloudtrail',
    resourceType: 'AWS::CloudTrail::Trail',
    displayName: 'CloudTrail',
    connections: ['s3', 'cloudwatch'],
    requiredProps: ['S3BucketName'],
    requiredConnections: ['s3'],
    recommendedConnections: [],
  },
  {
    id: 'config',
    resourceType: 'AWS::Config::ConfigurationRecorder',
    displayName: 'AWS Config',
    connections: ['s3', 'iam-role'],
    requiredProps: ['RoleARN'],
    requiredConnections: [],
    recommendedConnections: [],
  },
  {
    id: 'kms',
    resourceType: 'AWS::KMS::Key',
    displayName: 'KMS Key',
    connections: ['s3', 'rds', 'ebs'],
    requiredProps: ['KeyPolicy'],
    requiredConnections: [],
    recommendedConnections: [],
  },
  {
    id: 'ssm',
    resourceType: 'AWS::SSM::Parameter',
    displayName: 'SSM Parameter Store',
    connections: ['lambda', 'ec2-instance'],
    requiredProps: ['Name', 'Type', 'Value'],
    requiredConnections: [],
    recommendedConnections: [],
  },
  {
    id: 'waf',
    resourceType: 'AWS::WAFv2::WebACL',
    displayName: 'WAF',
    connections: ['cloudfront', 'apigw'],
    requiredProps: ['Scope', 'DefaultAction'],
    requiredConnections: ['apigw', 'cloudfront'],
    recommendedConnections: [],
  },
  {
    id: 'vpc',
    resourceType: 'AWS::EC2::VPC',
    displayName: 'VPC',
    connections: ['subnet', 'nat-gateway', 'internet-gateway'],
    requiredProps: ['CidrBlock'],
    requiredConnections: [],
    recommendedConnections: ['subnet', 'igw', 'nat-gateway'],
  },
  {
    id: 'subnet',
    resourceType: 'AWS::EC2::Subnet',
    displayName: 'Subnet',
    connections: ['ec2-instance', 'rds', 'elb', 'asg', 'nat-gateway'],
    requiredProps: ['VpcId', 'CidrBlock'],
    requiredConnections: ['vpc'],
    recommendedConnections: [],
  },
  {
    id: 'nat-gateway',
    resourceType: 'AWS::EC2::NatGateway',
    displayName: 'NAT Gateway',
    connections: ['subnet', 'elastic-ip'],
    requiredProps: ['SubnetId', 'AllocationId'],
    requiredConnections: ['subnet', 'elastic-ip'],
    recommendedConnections: [],
  },
  {
    id: 'igw',
    resourceType: 'AWS::EC2::InternetGateway',
    displayName: 'Internet Gateway',
    connections: ['vpc'],
    requiredProps: [],
    requiredConnections: ['vpc'],
    recommendedConnections: [],
  },
  {
    id: 'nacl',
    resourceType: 'AWS::EC2::NetworkAcl',
    displayName: 'Network ACL',
    connections: ['subnet'],
    requiredProps: ['VpcId'],
    requiredConnections: ['vpc'],
    recommendedConnections: [],
  },
  {
    id: 'sg',
    resourceType: 'AWS::EC2::SecurityGroup',
    displayName: 'Security Group',
    connections: ['ec2-instance', 'rds', 'elb', 'aurora', 'elasticache'],
    requiredProps: ['GroupDescription', 'VpcId'],
    requiredConnections: ['vpc'],
    recommendedConnections: [],
  },
]
