export const awsServiceData = [
  {
    id: 'iam-role',
    resourceType: 'AWS::IAM::Role',
    displayName: 'IAM Role',
    config: {
      RoleName: 'string',
      AssumeRolePolicyDocument: 'json',
    },
    connections: ['ec2-instance', 'lambda', 'apigateway'],
  },
  {
    id: 'ec2-instance',
    resourceType: 'AWS::EC2::Instance',
    displayName: 'EC2 Instance',
    config: {
      InstanceType: 'string',
      ImageId: 'string',
      KeyName: 'string',
      SubnetId: 'string',
      SecurityGroupIds: ['string'],
    },
    connections: ['iam-role', 'ec2-eip', 'ec2-ebs', 'efs', 'subnet', 'security-group'],
  },
  {
    id: 'ec2-eip',
    resourceType: 'AWS::EC2::EIP',
    displayName: 'Elastic IP',
    config: {
      Domain: 'string',
    },
    connections: ['ec2-instance', 'nat-gateway'],
  },
  {
    id: 'ec2-ebs',
    resourceType: 'AWS::EC2::Volume',
    displayName: 'EBS Volume',
    config: {
      Size: 'number',
      VolumeType: 'string',
      AvailabilityZone: 'string',
    },
    connections: ['ec2-instance'],
  },
  {
    id: 'efs',
    resourceType: 'AWS::EFS::FileSystem',
    displayName: 'EFS',
    config: {
      PerformanceMode: 'string',
      ThroughputMode: 'string',
      Encrypted: 'boolean',
    },
    connections: ['ec2-instance'],
  },
  {
    id: 'elb',
    resourceType: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
    displayName: 'Elastic Load Balancer',
    config: {
      Type: 'application|network',
      Subnets: ['string'],
      SecurityGroups: ['string'],
    },
    connections: ['ec2-instance', 'asg', 'subnet', 'security-group'],
  },
  {
    id: 'asg',
    resourceType: 'AWS::AutoScaling::AutoScalingGroup',
    displayName: 'Auto Scaling Group',
    config: {
      MinSize: 'number',
      MaxSize: 'number',
      DesiredCapacity: 'number',
      LaunchConfigurationName: 'string',
    },
    connections: ['ec2-instance', 'elb', 'subnet'],
  },
  {
    id: 'rds',
    resourceType: 'AWS::RDS::DBInstance',
    displayName: 'RDS Instance',
    config: {
      DBInstanceClass: 'string',
      Engine: 'string',
      MasterUsername: 'string',
      MasterUserPassword: 'string',
      AllocatedStorage: 'number',
    },
    connections: ['subnet', 'security-group'],
  },
  {
    id: 'aurora',
    resourceType: 'AWS::RDS::DBCluster',
    displayName: 'Aurora Cluster',
    config: {
      Engine: 'aurora-mysql|aurora-postgresql',
      MasterUsername: 'string',
      MasterUserPassword: 'string',
    },
    connections: ['subnet', 'security-group'],
  },
  {
    id: 'elasticache',
    resourceType: 'AWS::ElastiCache::CacheCluster',
    displayName: 'ElasticCache',
    config: {
      CacheNodeType: 'string',
      Engine: 'redis|memcached',
      NumCacheNodes: 'number',
    },
    connections: ['subnet', 'security-group'],
  },
  {
    id: 's3',
    resourceType: 'AWS::S3::Bucket',
    displayName: 'S3 Bucket',
    config: {
      BucketName: 'string',
      VersioningConfiguration: 'enabled|disabled',
      AccessControl: 'string',
    },
    connections: ['cloudfront', 'lambda', 'apigateway'],
  },
  {
    id: 'cloudfront',
    resourceType: 'AWS::CloudFront::Distribution',
    displayName: 'CloudFront',
    config: {
      Enabled: 'boolean',
      DefaultRootObject: 'string',
    },
    connections: ['s3'],
  },
  {
    id: 'sqs',
    resourceType: 'AWS::SQS::Queue',
    displayName: 'SQS Queue',
    config: {
      QueueName: 'string',
      VisibilityTimeout: 'number',
      MessageRetentionPeriod: 'number',
    },
    connections: ['lambda', 'sns'],
  },
  {
    id: 'sns',
    resourceType: 'AWS::SNS::Topic',
    displayName: 'SNS Topic',
    config: {
      TopicName: 'string',
      DisplayName: 'string',
    },
    connections: ['sqs', 'lambda'],
  },
  {
    id: 'kinesis',
    resourceType: 'AWS::Kinesis::Stream',
    displayName: 'Kinesis Data Stream',
    config: {
      ShardCount: 'number',
    },
    connections: ['lambda'],
  },
  {
    id: 'mq',
    resourceType: 'AWS::AmazonMQ::Broker',
    displayName: 'Amazon MQ',
    config: {
      BrokerName: 'string',
      EngineType: 'ActiveMQ|RabbitMQ',
      HostInstanceType: 'string',
    },
    connections: ['lambda'],
  },
  {
    id: 'apigateway',
    resourceType: 'AWS::ApiGateway::RestApi',
    displayName: 'API Gateway',
    config: {
      Name: 'string',
      EndpointConfiguration: 'EDGE|REGIONAL|PRIVATE',
    },
    connections: ['lambda', 's3'],
  },
  {
    id: 'lambda',
    resourceType: 'AWS::Lambda::Function',
    displayName: 'Lambda Function',
    config: {
      FunctionName: 'string',
      Handler: 'string',
      Runtime: 'string',
      MemorySize: 'number',
      Timeout: 'number',
    },
    connections: ['s3', 'sns', 'sqs', 'apigateway', 'iam-role', 'stepfunctions'],
  },
  {
    id: 'stepfunctions',
    resourceType: 'AWS::StepFunctions::StateMachine',
    displayName: 'Step Functions',
    config: {
      StateMachineName: 'string',
      DefinitionString: 'json',
    },
    connections: ['lambda'],
  },
  {
    id: 'cognito',
    resourceType: 'AWS::Cognito::UserPool',
    displayName: 'Cognito User Pool',
    config: {
      UserPoolName: 'string',
      AliasAttributes: ['string'],
    },
    connections: ['apigateway', 'lambda'],
  },
  {
    id: 'dynamodb',
    resourceType: 'AWS::DynamoDB::Table',
    displayName: 'DynamoDB',
    config: {
      TableName: 'string',
      AttributeDefinitions: 'json',
      KeySchema: 'json',
      BillingMode: 'PAY_PER_REQUEST|PROVISIONED',
    },
    connections: ['lambda'],
  },
  {
    id: 'documentdb',
    resourceType: 'AWS::DocDB::DBCluster',
    displayName: 'DocumentDB',
    config: {
      DBClusterIdentifier: 'string',
      EngineVersion: 'string',
      MasterUsername: 'string',
      MasterUserPassword: 'string',
    },
    connections: ['subnet', 'security-group'],
  },
  {
    id: 'neptune',
    resourceType: 'AWS::Neptune::DBCluster',
    displayName: 'Neptune',
    config: {
      DBClusterIdentifier: 'string',
      EngineVersion: 'string',
    },
    connections: ['subnet', 'security-group'],
  },
  {
    id: 'timestream',
    resourceType: 'AWS::Timestream::Database',
    displayName: 'Timestream',
    config: {
      DatabaseName: 'string',
    },
    connections: [],
  },
  {
    id: 'athena',
    resourceType: 'AWS::Athena::WorkGroup',
    displayName: 'Athena',
    config: {
      Name: 'string',
      State: 'ENABLED|DISABLED',
    },
    connections: ['s3'],
  },
  {
    id: 'redshift',
    resourceType: 'AWS::Redshift::Cluster',
    displayName: 'Redshift',
    config: {
      ClusterType: 'single-node|multi-node',
      NodeType: 'string',
      NumberOfNodes: 'number',
    },
    connections: ['subnet', 'security-group'],
  },
  {
    id: 'opensearch',
    resourceType: 'AWS::OpenSearchService::Domain',
    displayName: 'OpenSearch',
    config: {
      DomainName: 'string',
      EngineVersion: 'string',
    },
    connections: ['subnet', 'security-group'],
  },
  {
    id: 'cloudwatch',
    resourceType: 'AWS::CloudWatch::Alarm',
    displayName: 'CloudWatch',
    config: {
      AlarmName: 'string',
      MetricName: 'string',
      Threshold: 'number',
    },
    connections: ['lambda', 'ec2-instance', 'rds'],
  },
  {
    id: 'cloudtrail',
    resourceType: 'AWS::CloudTrail::Trail',
    displayName: 'CloudTrail',
    config: {
      TrailName: 'string',
      S3BucketName: 'string',
    },
    connections: ['s3', 'cloudwatch'],
  },
  {
    id: 'config',
    resourceType: 'AWS::Config::ConfigurationRecorder',
    displayName: 'AWS Config',
    config: {
      Name: 'string',
      RoleARN: 'string',
    },
    connections: ['s3', 'iam-role'],
  },
  {
    id: 'kms',
    resourceType: 'AWS::KMS::Key',
    displayName: 'KMS Key',
    config: {
      Description: 'string',
      KeyPolicy: 'json',
    },
    connections: ['s3', 'rds', 'ebs'],
  },
  {
    id: 'ssm-parameter',
    resourceType: 'AWS::SSM::Parameter',
    displayName: 'SSM Parameter Store',
    config: {
      Name: 'string',
      Type: 'String|SecureString',
      Value: 'string',
    },
    connections: ['lambda', 'ec2-instance'],
  },
  {
    id: 'waf',
    resourceType: 'AWS::WAFv2::WebACL',
    displayName: 'WAF',
    config: {
      Name: 'string',
      Scope: 'CLOUDFRONT|REGIONAL',
    },
    connections: ['cloudfront', 'apigateway'],
  },
  {
    id: 'vpc',
    resourceType: 'AWS::EC2::VPC',
    displayName: 'VPC',
    config: {
      CidrBlock: 'string',
      EnableDnsSupport: 'boolean',
    },
    connections: ['subnet', 'nat-gateway', 'internet-gateway'],
  },
  {
    id: 'subnet',
    resourceType: 'AWS::EC2::Subnet',
    displayName: 'Subnet',
    config: {
      CidrBlock: 'string',
      AvailabilityZone: 'string',
    },
    connections: ['ec2-instance', 'rds', 'elb', 'asg', 'nat-gateway'],
  },
  {
    id: 'nat-gateway',
    resourceType: 'AWS::EC2::NatGateway',
    displayName: 'NAT Gateway',
    config: {
      SubnetId: 'string',
      AllocationId: 'string',
    },
    connections: ['subnet', 'ec2-eip'],
  },
  {
    id: 'internet-gateway',
    resourceType: 'AWS::EC2::InternetGateway',
    displayName: 'Internet Gateway',
    config: {
      Tags: 'json',
    },
    connections: ['vpc'],
  },
  {
    id: 'nacl',
    resourceType: 'AWS::EC2::NetworkAcl',
    displayName: 'Network ACL',
    config: {
      VpcId: 'string',
    },
    connections: ['subnet'],
  },
  {
    id: 'security-group',
    resourceType: 'AWS::EC2::SecurityGroup',
    displayName: 'Security Group',
    config: {
      GroupDescription: 'string',
      VpcId: 'string',
    },
    connections: ['ec2-instance', 'rds', 'elb', 'aurora', 'elasticache'],
  },
]
